name: Docker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 3 * * *'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: grostim/fava-docker
  UPLOAD_RELEASE: ture

jobs:
  # On fait les tests dans tous les cas : pull et PR
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
